export const ProductsData = [
  {
    id: 1,
    title: "Camiseta de algodón",
    description: "Camiseta cómoda de algodón para uso diario.",
    price: 19.99,
    stock: 50,
    brand: "Marca A",
    category: "Camisetas",
    thumbnail: "url_de_la_imagen_1",
    images: ["url_de_imagen_1_1", "url_de_imagen_1_2", "url_de_imagen_1_3"],
  },
  {
    id: 2,
    title: "Pantalones vaqueros",
    description: "Pantalones vaqueros modernos y ajustados.",
    price: 39.99,
    stock: 30,
    brand: "Marca B",
    category: "Pantalones",
    thumbnail: "url_de_la_imagen_2",
    images: ["url_de_imagen_2_1", "url_de_imagen_2_2", "url_de_imagen_2_3"],
  },
  {
    id: 3,
    title: "Vestido floral",
    description: "Vestido floral perfecto para ocasiones especiales.",
    price: 49.99,
    stock: 20,
    brand: "Marca C",
    category: "Vestidos",
    thumbnail: "url_de_la_imagen_3",
    images: ["url_de_imagen_3_1", "url_de_imagen_3_2", "url_de_imagen_3_3"],
  },
  {
    id: 4,
    title: "Zapatillas deportivas",
    description: "Zapatillas cómodas para correr o hacer ejercicio.",
    price: 59.99,
    stock: 40,
    brand: "Marca D",
    category: "Calzado",
    thumbnail: "url_de_la_imagen_4",
    images: ["url_de_imagen_4_1", "url_de_imagen_4_2", "url_de_imagen_4_3"],
  },
  {
    id: 5,
    title: "Abrigo de invierno",
    description: "Abrigo elegante para mantenerse cálido en invierno.",
    price: 89.99,
    stock: 15,
    brand: "Marca E",
    category: "Abrigos",
    thumbnail: "url_de_la_imagen_5",
    images: ["url_de_imagen_5_1", "url_de_imagen_5_2", "url_de_imagen_5_3"],
  },
  {
    id: 6,
    title: "Sombrero de verano",
    description: "Sombrero ligero y elegante para días soleados.",
    price: 14.99,
    stock: 100,
    brand: "Marca F",
    category: "Accesorios",
    thumbnail: "url_de_la_imagen_6",
    images: ["url_de_imagen_6_1", "url_de_imagen_6_2", "url_de_imagen_6_3"],
  },
  {
    id: 7,
    title: "Chaqueta de cuero",
    description: "Chaqueta de cuero genuino para un look elegante.",
    price: 129.99,
    stock: 25,
    brand: "Marca G",
    category: "Chaquetas",
    thumbnail: "url_de_la_imagen_7",
    images: ["url_de_imagen_7_1", "url_de_imagen_7_2", "url_de_imagen_7_3"],
  },
  {
    id: 8,
    title: "Sudadera con capucha",
    description: "Sudadera con capucha cómoda y abrigada.",
    price: 34.99,
    stock: 35,
    brand: "Marca H",
    category: "Sudaderas",
    thumbnail: "url_de_la_imagen_8",
    images: ["url_de_imagen_8_1", "url_de_imagen_8_2", "url_de_imagen_8_3"],
  },
  {
    id: 9,
    title: "Bikini de playa",
    description: "Conjunto de bikini para disfrutar del sol en la playa.",
    price: 29.99,
    stock: 50,
    brand: "Marca I",
    category: "Ropa de Playa",
    thumbnail: "url_de_la_imagen_9",
    images: ["url_de_imagen_9_1", "url_de_imagen_9_2", "url_de_imagen_9_3"],
  },
  {
    id: 10,
    title: "Corbata elegante",
    description: "Corbata de seda para ocasiones formales.",
    price: 24.99,
    stock: 40,
    brand: "Marca J",
    category: "Accesorios",
    thumbnail: "url_de_la_imagen_10",
    images: ["url_de_imagen_10_1", "url_de_imagen_10_2", "url_de_imagen_10_3"],
  },
];
